CREATE DATABASE QLXUAT
ON(NAME='QLXUAT_DATA',FILENAME='D:\BTMONHOC\SQL server\QLXUAT.MDF')
LOG ON(NAME='QLXUAT_LOG',FILENAME='D:\BTMONHOC\SQL server\QLXUAT.LDF')
go
USE QLXUAT
GO
--TAO TABLE LOAI
CREATE TABLE LOAI
(
	MALOAI INT CONSTRAINT ML_PK PRIMARY KEY,
	TENLOAI NVARCHAR(30) NOT NULL
)
GO
-- TAO BANG NHAN VIEN
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(5)CONSTRAINT NV_PK PRIMARY KEY,
	HOTEN NVARCHAR(50),
	NGAYSINH SMALLDATETIME CONSTRAINT NS_CHECK CHECK(YEAR(GETDATE())-YEAR(NGAYSINH) BETWEEN 18 AND 55),
	PHAI INT CHECK(PHAI IN(0,1))
)
GO
-- TAO BANG SAN PHAM
CREATE TABLE SANPHAM 
(
	MASP INT CONSTRAINT SP_PK PRIMARY KEY,
	TENSP NVARCHAR(30) UNIQUE,
	MALOAI INT CONSTRAINT SP_FK FOREIGN KEY REFERENCES LOAI(MALOAI) 
)
GO
-- TAO BANG PHIEU XUAT
CREATE TABLE PHIEUXUAT
(
	MAPX INT IDENTITY(1,1) CONSTRAINT PX_PK PRIMARY KEY, -- MA PHIEU XUAT TU DONG TANG
	NGAYLAP SMALLDATETIME,
	MANV VARCHAR(5) CONSTRAINT PX_FK FOREIGN KEY  REFERENCES NHANVIEN(MANV)
)
GO
-- CHI TIET PHIEU XUAT
CREATE TABLE CTPX
(
	MAPX INT CONSTRAINT CTPX_MHD_FK FOREIGN KEY REFERENCES PHIEUXUAT(MAPX), 
	MASP INT CONSTRAINT CTPX_MVT_FK FOREIGN KEY REFERENCES SANPHAM(MASP),
	SOLUONG INT CONSTRAINT SL_CHECK CHECK(SOLUONG>0),
	CONSTRAINT CTPX_PK PRIMARY KEY(MAPX,MASP)
)
GO
--Insert data to table LOAI--
INSERT INTO LOAI VALUES(1,N'Vật liệu xây dựng')
INSERT INTO LOAI VALUES(2,N'Hàng tiêu dùng')
INSERT INTO LOAI VALUES(3,N'Ngũ cốc')
--Insert data to table KHACHHANG--
INSERT INTO SANPHAM VALUES(1,N'Xi măng',1)
INSERT INTO SANPHAM VALUES(2,N'Gạch',1)
INSERT INTO SANPHAM VALUES(3,N'Gạo nàng hương',3)
INSERT INTO SANPHAM VALUES(4,N'Bột mì',3)
INSERT INTO SANPHAM VALUES(5,N'Kệ chén',2)
INSERT INTO SANPHAM VALUES(6,N'Đậu xanh',3)
SET DATEFORMAT DMY
--Insert data to table NHANVIEN--
INSERT INTO NHANVIEN VALUES('NV01',N'Nguyễn Mai Thi','15/5/1982',0)
INSERT INTO NHANVIEN VALUES('NV02',N'Trần Đình Chiến','2/12/1980',1)
INSERT INTO NHANVIEN VALUES('NV03',N'Lê Thị Chi','23/1/1979',0)
--INSERT PHIEUXUAT
INSERT INTO PHIEUXUAT VALUES('12/3/2010','NV01')
INSERT INTO PHIEUXUAT VALUES('3/2/2010','NV02')
INSERT INTO PHIEUXUAT VALUES('1/6/2010','NV03')
INSERT INTO PHIEUXUAT VALUES('16/6/2010','NV01')
--Insert data to table CHITIETXUAT--
INSERT INTO CTPX VALUES(1,1,10)
INSERT INTO CTPX VALUES(1,2,15)
INSERT INTO CTPX VALUES(1,3,5)
INSERT INTO CTPX VALUES(2,2,20)
INSERT INTO CTPX VALUES(3,1,20)
INSERT INTO CTPX VALUES(3,3,25)
INSERT INTO CTPX VALUES(4,5,12)


--1.	Cho biết mã sản phẩm, tên sản phẩm, tổng số lượng 
--xuất của từng sản phẩm trong năm 2010. Lấy dữ liệu từ 
--View này sắp xếp tăng dần theo tên sản phẩm.
select s.MASP,s.TENSP,sum(c.soluong) as TONGSLTUNGSP
from SANPHAM s,CTPX c,PHIEUXUAT p
where s.MASP=c.MASP and p.MAPX=c.MAPX and year(p.NGAYLAP)=2010
group by s.MASP,s.TENSP

--2.	Cho biết mã sản phẩm, tên sản phẩm, tên loại sản phẩm mà đã được bán từ ngày 1/1/2010 đến 30/6/2010.
--3.	Cho biết số lượng sản phẩm trong từng loại sản phẩm gồm các thông tin: mã loại sản phẩm, tên loại sản phẩm, số lượng các sản phẩm.
--4.	Cho biết tổng số lượng phiếu xuất trong tháng 6 năm 2010.
--5.	Cho biết thông tin về các phiếu xuất mà nhân viên có mã NV01 đã xuất.

